version: '3.8'

services:
  web:
    image: nginx:latest
    hostname: web
    environment:
      TZ: "Asia/Seoul"
    restart: always
    volumes:
      - ${dir.nginx.log}:/usr/local/nginx/log
      - ${file.nginx.conf}:/etc/nginx/nginx.conf:ro
      - ${dir.certbot.main}:/etc/nginx/ssl
      - ${dir.certbot.public}:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - wikinet

  certbot:
    image: certbot/certbot:latest
    hostname: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your@email.com --agree-tos --no-eff-email -d your.domain.com
    volumes:
      - ${dir.certbot.main}:/etc/letsencrypt
      - ${dir.certbot.logs}:/var/log/letsencrypt
      - ${dir.certbot.public}:/var/www/certbot

  db:
    image: postgres:11
    hostname: db
    environment:
      POSTGRES_PASSWORD_FILE: /etc/wiki/.db-secret
      POSTGRES_DB: wiki
      POSTGRES_USER: wiki
      TZ: "Asia/Seoul"
    volumes:
      - ${file.db.secret}:/etc/wiki/.db-secret:ro
      - ${dir.db.data}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - wikinet

  wiki:
    image: requarks/wiki:2
    hostname: wiki
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASS_FILE: /etc/wiki/.db-secret
      DB_USER: wiki
      DB_NAME: wiki
      UPGRADE_COMPANION: 1
      TZ: "Asia/Seoul"
    volumes:
      - ${file.db.secret}:/etc/wiki/.db-secret:ro
      - ${file.storage.github.pem}:/etc/wiki/github.pem:ro
      - ${dir.storage.backup}:/etc/wiki/backup
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wikinet

  wiki-update-companion:
    image: requarks/wiki-update-companion:latest
    hostname: wiki-update-companion
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - wikinet

  kroki:
    image: yuzutech/kroki
    hostname: kroki 
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    restart: unless-stopped
    networks:
      - wikinet
  blockdiag:
    image: yuzutech/kroki-blockdiag
    hostname: blockdiag 
    restart: unless-stopped
    networks:
      - wikinet
  mermaid:
    image: yuzutech/kroki-mermaid
    hostname: mermaid 
    restart: unless-stopped
    networks:
      - wikinet
  bpmn:
    image: yuzutech/kroki-bpmn
    hostname: bpmn 
    restart: unless-stopped
    networks:
      - wikinet
  excalidraw:
    image: yuzutech/kroki-excalidraw
    hostname: excalidraw 
    restart: unless-stopped
    networks:
      - wikinet

networks:
  wikinet:
    driver: bridge