version: '3.8'

services:
  web:
    image: nginx:latest
    restart: always
    volumes:
      - ./logs:/var/log/nginx
      - ./logrotate-nginx.conf:/etc/logrotate.d/nginx:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    command: >
      bash -c "apt-get update && 
               apt-get install -y logrotate &&
               nginx -g 'daemon off;'"
    networks:
      - wikinet

  db:
    image: postgres:11
    hostname: db
    environment:
      POSTGRES_PASSWORD_FILE: /etc/wiki/.db-secret
      POSTGRES_DB: wiki
      POSTGRES_USER: wiki
    volumes:
      - ./db-secret:/etc/wiki/.db-secret:ro
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - wikinet

  wiki:
    image: requarks/wiki:2
    hostname: wiki
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_PASS_FILE: /etc/wiki/.db-secret
      DB_USER: wiki
      DB_NAME: wiki
      UPGRADE_COMPANION: 1
    volumes:
      - ./db-secret:/etc/wiki/.db-secret:ro
      - ./backup:/etc/wiki/backup
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wikinet

  wiki-update-companion:
    image: requarks/wiki-update-companion:latest
    hostname: wiki-update-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - wikinet

  kroki:
    image: yuzutech/kroki
    hostname: kroki 
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    restart: unless-stopped
    networks:
      - wikinet
  blockdiag:
    image: yuzutech/kroki-blockdiag
    hostname: blockdiag 
    restart: unless-stopped
    networks:
      - wikinet
  mermaid:
    image: yuzutech/kroki-mermaid
    hostname: mermaid 
    restart: unless-stopped
    networks:
      - wikinet
  bpmn:
    image: yuzutech/kroki-bpmn
    hostname: bpmn 
    restart: unless-stopped
    networks:
      - wikinet
  excalidraw:
    image: yuzutech/kroki-excalidraw
    hostname: excalidraw 
    restart: unless-stopped
    networks:
      - wikinet

networks:
  wikinet:
    driver: bridge